import type { Metadata } from 'next';
import { sora, inter, brandKitFontVariables } from '@/lib/fonts';
import { AuthProvider } from '@/lib/AuthProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'BrandKit AI — Generate a starter brand identity in seconds',
  description:
    'Get a color palette, font pairing, taglines, brand voice guide, and logo concept for your new business — generated by AI, free to start.',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{
          __html: `
            (function() {
              try {
                var t = localStorage.getItem('theme');
                if (t === 'dark' || (!t && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark');
                }
              } catch(e) {}
            })();
          `,
        }} />
      </head>
      <body className={`${sora.variable} ${inter.variable} ${brandKitFontVariables} font-body`}>
        <a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 focus:z-50 focus:bg-primary focus:text-white focus:px-4 focus:py-2 focus:rounded-lg">
          Skip to main content
        </a>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
