'use client';

import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';
import { BrandKit } from '@/types/brandkit';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: '#111827',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    marginTop: 16,
    borderBottom: '1 solid #e5e7eb',
    paddingBottom: 4,
  },
  tagline: {
    fontSize: 13,
    fontStyle: 'italic',
    marginBottom: 6,
    color: '#4f46e5',
  },
  swatchRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  swatch: {
    width: 80,
    height: 60,
    marginRight: 8,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swatchText: {
    fontSize: 8,
    color: '#fff',
    textAlign: 'center',
  },
  swatchTextDark: {
    fontSize: 8,
    color: '#000',
    textAlign: 'center',
  },
  fontRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  fontBox: {
    flex: 1,
    border: '1 solid #e5e7eb',
    borderRadius: 4,
    padding: 12,
    marginRight: 8,
  },
  fontLabel: {
    fontSize: 9,
    color: '#6b7280',
    marginBottom: 4,
  },
  fontName: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  voiceBox: {
    border: '1 solid #e5e7eb',
    borderRadius: 4,
    padding: 10,
    marginBottom: 8,
  },
  voiceTone: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  voiceDo: {
    fontSize: 10,
    color: '#059669',
    marginBottom: 2,
  },
  voiceDont: {
    fontSize: 10,
    color: '#dc2626',
  },
  logoBox: {
    border: '1 solid #e5e7eb',
    borderRadius: 4,
    padding: 12,
  },
  logoSstyle: {
    fontSize: 10,
    color: '#6b7280',
    marginBottom: 4,
  },
  logoDesc: {
    fontSize: 11,
    lineHeight: 1.5,
  },
});

export default function BrandKitPDF({ kit }: { kit: BrandKit }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{kit.brandName}</Text>
        <Text style={styles.subtitle}>Brand identity kit — generated by BrandKit AI</Text>

        <Text style={styles.sectionTitle}>Taglines</Text>
        {kit.taglines.map((t, i) => (
          <Text key={i} style={styles.tagline}>"{t}"</Text>
        ))}

        <Text style={styles.sectionTitle}>Color palette</Text>
        <View style={styles.swatchRow}>
          {kit.palette.map((c, i) => {
            const isLight = parseInt(c.hex.slice(1, 3), 16) > 200;
            return (
              <View key={i} style={[styles.swatch, { backgroundColor: c.hex }]}>
                <Text style={isLight ? styles.swatchTextDark : styles.swatchText}>{c.name}</Text>
                <Text style={isLight ? styles.swatchTextDark : styles.swatchText}>{c.hex}</Text>
              </View>
            );
          })}
        </View>

        <Text style={styles.sectionTitle}>Typography</Text>
        <View style={styles.fontRow}>
          <View style={styles.fontBox}>
            <Text style={styles.fontLabel}>Display</Text>
            <Text style={styles.fontName}>{kit.typography.display}</Text>
          </View>
          <View style={styles.fontBox}>
            <Text style={styles.fontLabel}>Body</Text>
            <Text style={styles.fontName}>{kit.typography.body}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Brand voice</Text>
        {kit.voice.map((v, i) => (
          <View key={i} style={styles.voiceBox}>
            <Text style={styles.voiceTone}>{v.tone}</Text>
            <Text style={styles.voiceDo}>Do: {v.doExample}</Text>
            <Text style={styles.voiceDont}>Don't: {v.dontExample}</Text>
          </View>
        ))}

        <Text style={styles.sectionTitle}>Logo concept</Text>
        <View style={styles.logoBox}>
          <Text style={styles.logoSstyle}>{kit.logoConcept.style}</Text>
          <Text style={styles.logoDesc}>{kit.logoConcept.description}</Text>
        </View>
      </Page>
    </Document>
  );
}
